name: Build and deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: # allow manual execution

permissions:
  contents: write
  pages: write
  actions: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: map-starter-kit-master

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up Environment Variables
        run: |
          if [ -z "${{ secrets.UPLOAD_MODE }}" ]; then
            echo "Error: UPLOAD_MODE is not set in GitHub Secrets."
            exit 1
          fi
          echo "UPLOAD_MODE=${{ secrets.UPLOAD_MODE }}" >> $GITHUB_ENV

          if [ "${{ secrets.UPLOAD_MODE }}" = "MAP_STORAGE" ]; then
            if [ -z "${{ secrets.MAP_STORAGE_API_KEY }}" ]; then
              echo "Error: MAP_STORAGE_API_KEY is not set in GitHub Secrets."
              exit 1
            fi
            if [ -z "${{ secrets.MAP_STORAGE_URL }}" ]; then
              echo "Error: MAP_STORAGE_URL is not set in GitHub Secrets."
              exit 1
            fi
            echo "MAP_STORAGE_API_KEY=${{ secrets.MAP_STORAGE_API_KEY }}" >> $GITHUB_ENV
            echo "MAP_STORAGE_URL=${{ secrets.MAP_STORAGE_URL }}" >> $GITHUB_ENV

            if [ -n "${{ secrets.UPLOAD_DIRECTORY }}" ]; then
              echo "UPLOAD_DIRECTORY=${{ secrets.UPLOAD_DIRECTORY }}" >> $GITHUB_ENV
            else
              USERNAME=${{ github.repository_owner }}
              REPO=${{ github.event.repository.name }}
              UPLOAD_DIRECTORY="${USERNAME}-${REPO}"
              echo "UPLOAD_DIRECTORY=$UPLOAD_DIRECTORY" >> $GITHUB_ENV
              echo "Warning: UPLOAD_DIRECTORY was not found; set to $UPLOAD_DIRECTORY."
            fi
          fi

      - name: Deploy using WA Map Storage
        if: ${{ env.UPLOAD_MODE == 'MAP_STORAGE' }}
        run: npm run upload-only

      - name: Deploy using Github Pages
        if: ${{ env.UPLOAD_MODE == 'GH_PAGES' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/
          BASE_BRANCH: master
